package com.github.sib_energy_craft.screen.property;

import org.jetbrains.annotations.NotNull;

import java.util.function.Supplier;

/**
 * @author sibmaks
 * @since 0.0.1
 */
public record TypedScreenProperty<T>(int id,
                                     @NotNull ScreenPropertyType<T> type,
                                     @NotNull Supplier<T> valueSupplier) {

    /** Get property value.<br/>
     * Property generated by calling {@link this#valueSupplier} each time
     *
     * @return property value
     */
    public T value() {
        return valueSupplier.get();
    }

}
